---
title: "Eric_Hirsch_624_Homework_5"
output: html_document
date: "2023-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

library(tidyverse)
library(tsibble)
library(fpp3)
library(EHData)
library(gridExtra)
library(fable)
library(readxl)

```

```{r}

dfATM <- as.data.frame(read_excel("D:\\RStudio\\CUNY_624\\Project1\\ATM624Data.xlsx"))

```

```{r}

summary(dfATM)
str(dfATM)

tsATM1 <- dfATM %>%
  filter(ATM=="ATM1")%>%
  mutate(xDate=as_date(DATE)) %>%
  as_tsibble(index=xDate) %>%
  dplyr::select(xDate, Cash)

tsATM2 <- dfATM %>%
  filter(ATM=="ATM2")%>%
  mutate(xDate=as_date(DATE)) %>%
  as_tsibble(index=xDate) %>%
  dplyr::select(xDate, Cash)

tsATM3 <- dfATM %>%
  filter(ATM=="ATM3")%>%
  mutate(xDate=as_date(DATE)) %>%
  as_tsibble(index=xDate) %>%
  dplyr::select(xDate, Cash)

tsATM4 <- dfATM %>%
  filter(ATM=="ATM4")%>%
  mutate(xDate=as_date(DATE)) %>%
  as_tsibble(index=xDate) %>%
  dplyr::select(xDate, Cash)

```
Start with ATM1

Handle Missings

```{r}

which(is.na(tsATM1$Cash))

InterpolateBetweenRows <- function(df, column, rowNumber) {

lo = rowNumber-1
hi = rowNumber+1

df1 <- filter(df, row_number() == lo)
df2 <- filter(df, row_number() == hi)
x = (df1[,column] + df2[,column])/2
df[rowNumber, column] = x
return (df)


}

q <- InterpolateBetweenRows(tsATM1, "Cash", 44)
q2 <- InterpolateBetweenRows(q, "Cash", 47)
q3 <- InterpolateBetweenRows(q2, "Cash", 53)
tsATM1a <- q3

which(is.na(tsATM2$Cash))

qq <- InterpolateBetweenRows(tsATM2, "Cash", 49)
qq2 <- InterpolateBetweenRows(qq, "Cash", 55)
tsATM2a <- qq2
```
Outliers

```{r}
dfCash1 <- as.data.frame(tsATM1a$Cash)
EHSummarize_SingleColumn_Boxplots(dfCash1)
EHSummarize_SingleColumn_Histograms(dfCash1)


```

Turn to monthly
```{r}
  
tsATM1b <- tsATM1a %>%
  as.data.frame() %>%
  group_by(Month=yearmonth(xDate)) %>%
  dplyr::summarize(MonthlyCash=sum(Cash)) %>%
  as_tsibble(index="Month")

autoplot(tsATM1a)
autoplot(tsATM1b)

  stl<- tsATM1a %>%
  stl(s.window ="periodic")
  autoplot(stl)

```


```{r}

train1m <- tsATM1b %>%
  filter_index(~ "2010 Feb")

fit1m <- tsATM1b %>%
  model(ETS(MonthlyCash ~ error("A") + trend("A") + season("N")))
  
fc1m <- fit1m %>%
  forecast(h = 3)

fc1m %>%
  autoplot(tsATM1b) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit1m)) +
  labs(y="Count", title="ATM1 - ETS AAN") +
  guides(colour = "none")

report(fit1m)
fc1m$.mean

```
do it a daily

```{r}
fit1d <- tsATM1a %>%
  model(ETS(Cash ~ error("A") + trend("A") + season("A")))
  
fc1d <- fit1d %>%
  forecast(h = 31)

fc1d %>%
  autoplot(tsATM1a) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit1d)) +
  labs(y="Count", title="ATM1 - ETS AAA") +
  guides(colour = "none")

report(fit1d)
sum(fc1d$.mean)



```

Outliers

```{r}

summary(tsATM4)
dfCash4 <- as.data.frame(tsATM4$Cash)
EHSummarize_SingleColumn_Boxplots(dfCash4)
EHSummarize_SingleColumn_Histograms(dfCash4)


```
Remove outlier

```{r}

tsATM4a <- tsATM4  %>%
  mutate(Cash=ifelse(Cash>10000, 109, Cash))

```

Turn to monthly
```{r}
  
tsATM4b <- tsATM4a %>%
  as.data.frame() %>%
  group_by(Month=yearmonth(xDate)) %>%
  dplyr::summarize(MonthlyCash=sum(Cash)) %>%
  as_tsibble(index="Month")

autoplot(tsATM4a)
autoplot(tsATM4b)

  stl<- tsATM4a %>%
  stl(s.window ="periodic")
  autoplot(stl)

```


```{r}

train4m <- tsATM4b %>%
  filter_index(~ "2010 Feb")

fit4m <- tsATM4b %>%
  model(ETS(MonthlyCash ~ error("A") + trend("A") + season("N")))
  
fc4m <- fit4m %>%
  forecast(h = 3)

fc4m %>%
  autoplot(tsATM4b) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit4m)) +
  labs(y="Count", title="ATM1 - ETS AAN") +
  guides(colour = "none")

report(fit4m)
fc4m$.mean

```
do it a daily

```{r}
fit4d <- tsATM4a %>%
  model(ETS(Cash ~ error("A") + trend("A") + season("A")))
  
fc4d <- fit4d %>%
  forecast(h = 31)

fc4d %>%
  autoplot(tsATM4a) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit1d)) +
  labs(y="Count", title="ATM1 - ETS AAA") +
  guides(colour = "none")

report(fit4d)
sum(fc4d$.mean)



```


Outliers

```{r}

summary(tsATM2a)
dfCash2 <- as.data.frame(tsATM2a$Cash)
EHSummarize_SingleColumn_Boxplots(dfCash2)
EHSummarize_SingleColumn_Histograms(dfCash2)


```

Turn to monthly
```{r}
  
tsATM2b <- tsATM2a %>%
  as.data.frame() %>%
  group_by(Month=yearmonth(xDate)) %>%
  dplyr::summarize(MonthlyCash=sum(Cash)) %>%
  as_tsibble(index="Month")

autoplot(tsATM2a)
autoplot(tsATM2b)

  stl<- tsATM2a %>%
  stl(s.window ="periodic")
  autoplot(stl)

```


```{r}

train2m <- tsATM2b %>%
  filter_index(~ "2010 Feb")

fit2m <- tsATM2b %>%
  model(ETS(MonthlyCash ~ error("A") + trend("A") + season("N")))
  
fc2m <- fit2m %>%
  forecast(h = 3)

fc2m %>%
  autoplot(tsATM2b) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit2m)) +
  labs(y="Count", title="ATM1 - ETS AAN") +
  guides(colour = "none")

report(fit2m)
fc2m$.mean

```
do it a daily

```{r}
fit4d <- tsATM4a %>%
  model(ETS(Cash ~ error("A") + trend("A") + season("A")))
  
fc4d <- fit4d %>%
  forecast(h = 31)

fc4d %>%
  autoplot(tsATM4a) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit1d)) +
  labs(y="Count", title="ATM1 - ETS AAA") +
  guides(colour = "none")

report(fit4d)
sum(fc4d$.mean)



```

Outliers

```{r}

summary(tsATM3)
dfCash3 <- as.data.frame(tsATM3$Cash)
EHSummarize_SingleColumn_Boxplots(dfCash3)
EHSummarize_SingleColumn_Histograms(dfCash3)


```
Remove outlier

```{r}

tsATM4a <- tsATM4  %>%
  mutate(Cash=ifelse(Cash>10000, 109, Cash))

```

Turn to monthly
```{r}
  
tsATM4b <- tsATM4a %>%
  as.data.frame() %>%
  group_by(Month=yearmonth(xDate)) %>%
  dplyr::summarize(MonthlyCash=sum(Cash)) %>%
  as_tsibble(index="Month")

autoplot(tsATM4a)
autoplot(tsATM4b)

  stl<- tsATM4a %>%
  stl(s.window ="periodic")
  autoplot(stl)

```


```{r}

train4m <- tsATM4b %>%
  filter_index(~ "2010 Feb")

fit4m <- tsATM4b %>%
  model(ETS(MonthlyCash ~ error("A") + trend("A") + season("N")))
  
fc4m <- fit4m %>%
  forecast(h = 3)

fc4m %>%
  autoplot(tsATM4b) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit4m)) +
  labs(y="Count", title="ATM1 - ETS AAN") +
  guides(colour = "none")

report(fit4m)
fc4m$.mean

```
do it a daily

```{r}
fit4d <- tsATM4a %>%
  model(ETS(Cash ~ error("A") + trend("A") + season("N")))
  
fc4d <- fit4d %>%
  forecast(h = 31)

fc4d %>%
  autoplot(tsATM4a) +
  geom_line(aes(y = .fitted), col="#D55E00",
            data = augment(fit1d)) +
  labs(y="Count", title="ATM1 - ETS AAN") +
  guides(colour = "none")

report(fit4d)
sum(fc4d$.mean)



```


