---
title: "Eric_Hirsch_624_Homework_4"
output: html_document
date: "2023-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

library(tidyverse)
library(tsibbledata)
library(tsibble)
library(forecast)
library(fpp3)
library(fable)
library(EHData)
library(gridExtra)

```

Exercises 1,2,3,4,7

__*1.Produce forecasts for the following series using whichever of NAIVE(y), SNAIVE(y) or RW(y ~ drift()) is more appropriate in each case:*__

__*1.a Australian Population (global_economy)*__

```{r}
library(mlbench)
data(Glass)

dfGlass <- Glass %>% 
  mutate(Type = as.numeric(Type))

summary(dfGlass)

```

```{r}

w <- EHSummarize_SingleColumn_Boxplots(dfGlass)
x <- EHSummarize_SingleColumn_Histograms(dfGlass)

grid.arrange(grobs=w[1:10], ncols=3)
grid.arrange(grobs=x[1:10], ncols=3)

a <- EHExplore_Multicollinearity(dfGlass, threshold=.6, printHighest = TRUE)

```

```{r}
library(caret)

 library("nnet")
test <- multinom(Type ~ ., data = dfGlass)
#a <- EHModel_Regression_StandardLM(dfGlass, "Type")
test

```

```{r}
devtools::install_github("ericonsi/EHData")
library(EHData)

df3 <- dfGlass %>%
  mutate(Ba=Ba+1, K=K+1, Fe=Fe+1, Mg=Mg+1)

Z <- EHPrepare_BoxCox(df3, "Al", print=TRUE)
Z1 <- EHPrepare_BoxCox(Z, "Ba", print=TRUE)
Z2 <- EHPrepare_BoxCox(Z1, "Fe", print=TRUE)
Z3 <- EHPrepare_BoxCox(Z2, "Mg", print=TRUE)

x <- Z3 %>%
  dplyr::select(Mg, K, Fe, Ba)

EHSummarize_SingleColumn_Histograms(x)

test <- multinom(Type ~ ., data = Z3)
test


```
```{r}
dfGlass2 <- dfGlass %>%
  filter(K<4, Fe<.5, Na <15) %>%
  mutate(Mg=log(Mg+1), K=log(K+1), Fe=log(Fe+1),Ba=log(Ba+1)) 

test <- multinom(Type ~ ., data = dfGlass2)
#a <- EHModel_Regression_StandardLM(dfGlass, "Type")
test


```
```{r}
library(mlbench)
data(Soybean)

dfSoybean <- Soybean 

summary(dfSoybean)
str(dfSoybean)

```

```{r}

dfSoybeanNum <- dfSoybean %>%
  dplyr::select(-Class, -date)  %>%
  mutate_all(as.numeric) %>%
  drop_na()

x <- EHExplore_Multicollinearity(dfSoybeanNum, threshold = .7, printHighest = TRUE)
```

```{r}

EHSummarize_MissingValues(dfSoybean)
```

