---
title: "Eric_Hirsch_624_Homework_1"
output: html_document
date: "2023-01-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

1. Use the help function to explore what the series gafa_stock, PBS, vic_elec and pelt represent.
* Use autoplot() to plot some of the series in these data sets.
* What is the time interval of each series?

```{r}

library(tidyverse)
library(tsibbledata)
library(tsibble)
library(forecast)
library(fpp2)
library(fable)

Explore <- function(ts)
{
  x <- deparse(substitute(ts))

  print("----------------------------------------")
  print(x)
  print(help(ts))
  print(summary(ts))
  print(autoplot(ts) +
    ggtitle(paste("Autoplot for ", x)))
  
  print(paste("Interval for", x, ":  "))
  interval(ts)
}

Explore(gafa_stock)
Explore(vic_elec)
Explore(pelt)

  print("----------------------------------------")
  print(paste("Interval for", "PBS", ":  "))
  interval(PBS)

```

2. Use filter() to find what days corresponded to the peak closing price for each of the four stocks in gafa_stock.

```{r}

tsGF <- gafa_stock %>%
  group_by(Symbol) %>%
  dplyr::filter(Close == max(Close))

tsGF


```


