---
title: "Eric_Hirsch_624_Homework_1"
output: html_document
date: "2023-01-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}

library(tidyverse)
library(tsibbledata)
library(tsibble)
library(forecast)
library(fpp2)
library(fpp3)
library(fable)
library(EHData)

Explore <- function(ts)
{
  x <- deparse(substitute(ts))

  print("----------------------------------------")
  print(x)
  print(help(ts))
  print(summary(ts))
  print(autoplot(ts) +
    ggtitle(paste("Autoplot for ", x)))
  
  print(paste("Interval for", x, ":  "))
  interval(ts)
}

timePlot <- function(ts, x, y, color) {
  
g <- ts %>%
  pivot_longer(-x) %>%
  ggplot(aes_string(x = pivot, y = y, color = color)) +
  geom_line() +
  ggtitle("No facet_grid") +  
  facet_grid(name ~ ., scales = "free_y") 

return (g)
  
}

```
```{r}

Explore(gafa_stock)
Explore(vic_elec)
Explore(pelt)

  print("----------------------------------------")
  print(paste("Interval for", "PBS", ":  "))
  interval(PBS)

```

```{r}
library(doParallel)

cl<-makePSOCKcluster(7)
  
registerDoParallel(cl)

dfCSD <- readr::read_csv("CSD1a.csv")

tsCSD <- dfCSD %>%
  mutate(Month = yearmonth(DateOfService)) %>%
  group_by(Month) %>%
  summarize(TotalServices = sum(CountOfServiceID)) %>%
  as_tsibble(index = Month)

tsCSD2 <- dfCSD %>%
  mutate(Month = yearmonth(DateOfService)) %>%
  group_by(Month, Program) %>%
  summarize(TotalServices = sum(CountOfServiceID)) %>%
  as_tsibble(index = Month, key=Program) %>%
  fill_gaps()

tsCSD_Bup <- tsCSD2 %>%
  filter(Program=="Buprenorphine")
  
autoplot(tsCSD)
autoplot(tsCSD2)
autoplot(tsCSD_Bup)

gg_season(tsCSD, TotalServices, labels = "both") +
  labs(y = "#",
       title = "Seasonal plot: Total Services") 

gg_season(tsCSD_Bup, TotalServices, labels = "both") +
  labs(y = "#",
       title = "Seasonal plot: Bup: Total Services") 

ACF(tsCSD, lag_max = 9) %>% autoplot()
ACF(tsCSD_Bup, lag_max = 9) %>% autoplot()

tsCSD %>%
  model(
    STL(TotalServices ~ trend(window = 7) +
                   season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

tsCSD_Bup %>%
  model(
    STL(TotalServices ~ trend(window = 7) +
                   season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

stopCluster(cl)

```

Create time plots of the following four time series: Bricks from aus_production, Lynx from pelt, Close from gafa_stock, Demand from vic_elec.

Use ? (or help()) to find out about the data in each series.
For the last plot, modify the axis labels and title.

```{r}



```

